# Generated by Django 3.1 on 2022-03-12 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appartment_listing', '0002_auto_20220305_1312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listings',
            name='propertyType',
            field=models.CharField(max_length=15, verbose_name='PropertyType'),
        ),
        migrations.AlterField(
            model_name='listings',
            name='purchaseType',
            field=models.CharField(max_length=8, verbose_name='PurchaseType'),
        ),
    ]
