# Generated by Django 3.1 on 2022-03-12 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appartment_listing', '0003_auto_20220312_0916'),
    ]

    operations = [
        migrations.AddField(
            model_name='scraper',
            name='scraper_image',
            field=models.CharField(blank=True, default=None, max_length=200, null=True, verbose_name='ScraperImage'),
        ),
        migrations.AlterField(
            model_name='listings',
            name='propertyType',
            field=models.CharField(default='House', max_length=15, verbose_name='PropertyType'),
        ),
        migrations.AlterField(
            model_name='listings',
            name='purchaseType',
            field=models.CharField(default='Buy', max_length=8, verbose_name='PurchaseType'),
        ),
    ]
