# Generated by Django 3.1 on 2022-03-26 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appartment_listing', '0004_auto_20220312_2015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scraper',
            name='scraper_id',
            field=models.AutoField(primary_key=True, serialize=False, unique=True, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='scraper',
            name='scraper_image',
            field=models.CharField(blank=True, default=None, max_length=200, null=True, unique=True, verbose_name='ScraperImage'),
        ),
        migrations.AlterField(
            model_name='scraper',
            name='scrapertitle',
            field=models.CharField(max_length=255, unique=True, verbose_name='ScraperTitle'),
        ),
    ]
