# Generated by Django 3.1 on 2022-02-16 18:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listings',
            name='bedroom',
            field=models.IntegerField(default=1, verbose_name='Bedroom'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='listings',
            name='description',
            field=models.TextField(blank=True, default=1, verbose_name='Description'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='listings',
            name='list_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now, verbose_name='List Date'),
        ),
    ]
